openapi: "3.0.0"
info:
  version: 1.0.0
  title: Connector Service
servers:
  - url: api/connector
paths:
  /connection:
    get:
      summary: GetActiveConnection
      operationId: getActiveConnection
      tags:
        -  connection
      responses:
        200:
          description: Schemas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConnectionStoreList'
    post:
      summary: CreateConnection
      operationId: createConnection
      tags:
        -  connection
      responses:
        200:
          description: Schemas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConnectionStatus'
    delete:
      summary: DestroyConnection
      operationId: destroyConnection
      tags:
        -  connection
      responses:
        200:
          description: Schemas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConnectionStatus'            
components:
  schemas:
    ConnectionStoreList:
      type: array
      items:
        $ref: '#/components/schemas/ConnectionStore'
    ConnectionStatus:
      required:
        - status
      properties:
        statuscode:
          type: number
          
          