# build environment
FROM node:13.12.0-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
RUN npm install react-scripts@3.4.1 -g --silent
COPY . ./
RUN npm run build

# production environment
FROM tomcat:jdk11-adoptopenjdk-hotspot

COPY ./app/build /usr/local/tomcat/webapps/
# Docker config
EXPOSE 8080

CMD [“catalina.sh”, “run”]