version: "3"
services:
  apiservice:
    image: apiservice
    environment:
      - AUTH_URL=authservice:8082
      - CONN_URL=connectorservice:8081
    depends_on:
      - authservice
      - connectorservice
    ports:
      - "8083:8083"
    links:
      - "authservice:authservice"
      - "connectorservice:connectorservice"
    networks:
      - linux-connector

  authservice:
    image: authservice
    networks:
      - linux-connector
 
  connectorservice:
    image: connectorservice
    environment:
      - AUTH_URL=authservice:8082
    depends_on:
      - authservice
    links:
      - "authservice:authservice"
    networks:
      - linux-connector

networks:
  linux-connector:
