openapi: "3.0.0"
info:
  version: 1.0.0
  title: Auth Service
servers:
  - url: api/auth
paths:
  /auth:
    patch:
      summary: Register
      operationId: register
      tags:
        -  auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        200:
          description: Schemas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
    post:
      summary: Authenticate
      operationId: authenticate
      tags:
        -  auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        200:
          description: Schemas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
    put:
      summary: VerifyToken
      operationId: verifyToken
      tags:
        -  auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Token'
      responses:
        200:
          description: Schemas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'     
components:
  schemas:
    Token:
      required:
        - token
      properties:
        token:
          type: string
    Login:
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 1
          maxLength: 40